Domain.Authentication.IntegrationTests/Domain.Authentication.IntegrationTests.csproj, Domain.Authentication.UnitTests/Domain.Authentication.UnitTests.csproj, Domain.Authentication/Domain.Authentication.csproj, Domain.Instructor/Domain.Instructor.csproj, Submarine.Api.sln
Added Domain.Authentication to contain MediatR queries/commands for JWT. Fixes #33.
=> SUBAPI-33: Added Domain.Authentication

Submarine Domain Authentication/Domain.Authentication.UnitTests/Queries/HashTextQueryHandlerTests.cs, Submarine Domain Authentication/Domain.Authentication.UnitTests/Settings/SubmarineTestAuthenticationSettings.cs, Submarine Domain Authentication/Domain.Authentication/Domain.Authentication.csproj, Submarine Domain Authentication/Domain.Authentication/Queries/HashText/HashTextQuery.cs, Submarine Domain Authentication/Domain.Authentication/Queries/HashText/HashTextQueryHandler.cs, Submarine Domain Authentication/Domain.Authentication/Settings/ISubmarineAuthenticationSettings.cs
=> SUBAPI-32: Added HashText Query

Submarine Domain Authentication/Domain.Authentication.UnitTests/Queries/CompareHashTextQueryHandlerTests.cs, Submarine Domain Authentication/Domain.Authentication/Queries/CompareHashText/CompareHashTextQuery.cs, Submarine Domain Authentication/Domain.Authentication/Queries/CompareHashText/CompareHashTextQueryHandler.cs
=> SUBAPI-61: Added CompareHashTextQuery

Submarine Domain Authentication/Domain.Authentication.UnitTests/Queries/HashTextQueryHandlerTests.cs, Submarine Domain Authentication/Domain.Authentication/Queries/HashText/HashTextQuery.cs, Submarine Domain Authentication/Domain.Authentication/Queries/HashText/HashTextQueryHandler.cs
=> SUBAPI-63: Renamed PlainTextPassword to PlainText

Submarine API/Api/Startup.cs, Submarine Domain/Domain.UnitTests/Extensions/ServiceCollectionExtensionTests.cs, Submarine Domain/Domain/Builders/SubmarineDatabaseBuilder.cs, Submarine Domain/Domain/Domain.csproj, Submarine Domain/Domain/Extensions/ServiceCollectionExtensions.cs
=> SUBAPI-67: Corrected Namespace for Domain

Submarine API/Api.Abstractions.UnitTests/Api.Abstractions.UnitTests.csproj, Submarine API/Api.Abstractions.UnitTests/Middleware/ExceptionMiddlewareTests.cs, Submarine API/Api.Abstractions/Api.Abstractions.csproj, Submarine API/Api.Abstractions/Middleware/ExceptionMiddleware.cs, Submarine Abstractions/Abstractions/Exceptions/ISubmarineException.cs, Submarine Abstractions/Abstractions/Exceptions/SubmarineException.cs, Submarine Abstractions/Abstractions/Exceptions/SubmarineExceptionCode.cs, Submarine Abstractions/Abstractions/Responses/ExceptionResponse.cs, Submarine.Api.sln
=> SUBAPI-71: Exception Middleware

Submarine API/Api.Abstractions.UnitTests/Api.Abstractions.UnitTests.csproj, Submarine API/Api.Abstractions.UnitTests/DocumentFilters/VersionDocumentFilterTests.cs, Submarine API/Api.Abstractions.UnitTests/OperationFilters/VersionOperationFilterTests.cs, Submarine API/Api.Abstractions/Api.Abstractions.csproj, Submarine API/Api.Abstractions/DocumentFilters/VersionDocumentFilter.cs, Submarine API/Api.Abstractions/Extensions/ApplicationBuilderExtensions.cs, Submarine API/Api.Abstractions/Extensions/ServiceCollectionExtensions.cs, Submarine API/Api.Abstractions/OperationFilters/VersionOperationFilter.cs, Submarine API/Api/Controllers/UserController.cs, Submarine API/Api/Properties/launchSettings.json, Submarine API/Api/Startup.cs
=> SUBAPI-45: Added Versioning

Domain License/Domain.License.IntegrationTests/Commands/InsertLicense/InsertLicenseCommandHandlerTests.cs, Domain License/Domain.License.IntegrationTests/Domain.License.IntegrationTests.csproj, Domain License/Domain.License.UnitTests/Commands/InsertLicense/InsertLicenseCommandBuilderTests.cs, Domain License/Domain.License.UnitTests/Commands/InsertLicense/InsertLicenseProductCommandBuilderTests.cs, Domain License/Domain.License.UnitTests/Domain.License.UnitTests.csproj, Domain License/Domain.License.UnitTests/Extensions/LicenseEntityExtensionTests.cs, Domain License/Domain.License/Commands/InsertLicense/InsertLicenseCommand.cs, Domain License/Domain.License/Commands/InsertLicense/InsertLicenseCommandBuilder.cs, Domain License/Domain.License/Commands/InsertLicense/InsertLicenseCommandHandler.cs, Domain License/Domain.License/Commands/InsertLicense/InsertLicenseProductCommand.cs, Domain License/Domain.License/Commands/InsertLicense/InsertLicenseProductCommandBuilder.cs, Domain License/Domain.License/Domain.License.csproj, Domain License/Domain.License/Entities/LicenseEntity.cs, Domain License/Domain.License/Entities/LicenseProductEntity.cs, Domain License/Domain.License/Extensions/InsertLicenseCommandExtensions.cs, Domain License/Domain.License/Extensions/InsertLicenseProductCommandExtensions.cs, Domain License/Domain.License/Stubs/LicenseProductStub.cs, Submarine.Api.sln, TestingUtilities/MongoIntegrationTests.cs, TestingUtilities/SubmarineAssert.cs, TestingUtilities/TestingUtilities.csproj
=> SUBAPI-79: Added Insert License Command

Submarine Domain License/Domain.License.IntegrationTests/Queries/GetLicenseByProductKeyQueryHandlerTests.cs, Submarine Domain License/Domain.License.UnitTests/Queries/GetLicenseByProductKey/GetLicenseByProductKeyQueryBuilderTests.cs, Submarine Domain License/Domain.License/Domain.License.csproj, Submarine Domain License/Domain.License/Queries/GetLicenseByProductKey/GetLicenseByProductKeyQuery.cs, Submarine Domain License/Domain.License/Queries/GetLicenseByProductKey/GetLicenseByProductKeyQueryBuilder.cs, Submarine Domain License/Domain.License/Queries/GetLicenseByProductKey/GetLicenseByProductKeyQueryHandler.cs
=> SUBAPI-81: Added Get License By Product Key Query

Submarine.Api.sln, Test Packs/IntegrationTestPack/MongoIntegrationTests.cs
=> SUBAPI-90: Removed TestUtilities

Submarine API/Api.Abstractions/Extensions/ServiceCollectionExtensions.cs, Submarine API/Api.Abstractions/Middleware/ExceptionMiddleware.cs, Submarine API/Api.IntegrationTests/Controllers/AuthenticationControllerTests.cs, Submarine API/Api.IntegrationTests/Controllers/UserControllerTests.cs, Test Packs/TestPack/DiagnoseaAssert.cs
=> SUBAPI-109: Moved to Newtonsoft

Submarine API/Api.Abstractions.Swagger/Api.Abstractions.Swagger.csproj, Submarine API/Api.Abstractions.Swagger/Examples/AuthenticateRequestExamplesProvider.cs, Submarine API/Api.Abstractions.Swagger/Examples/GetUserRequestExamplesProvider.cs, Submarine API/Api.Abstractions.Swagger/Examples/RegisterRequestExamplesProvider.cs, Submarine API/Api.Abstractions.Swagger/Extensions/ServiceCollectionExtensions.cs, Submarine API/Api/Api.csproj, Submarine API/Api/Controllers/AuthenticationController.cs, Submarine API/Api/Controllers/UserController.cs, Submarine API/Api/Startup.cs, Submarine Abstractions/Abstractions.Interchange/Requests/User/GetUserRequest.cs, Submarine Domain Abstractions/Domain.Abstractions/Builders/SubmarineDatabaseBuilder.cs
Fixes #107.
See descriptions added:
=> SUBAPI-104: Added Swagger Examples

Submarine API/Api.Abstractions/Extensions/ApplicationBuilderExtensions.cs, Submarine API/Api.IntegrationTests/Controllers/AuthenticationControllerTests.cs, Submarine Abstractions/Abstractions.Exceptions/SubmarineDataAlreadyExistsException.cs, Submarine Abstractions/Abstractions.Exceptions/SubmarineExceptionCode.cs, Submarine Abstractions/Abstractions.Exceptions/UserExceptionMessages.cs, Submarine Domain/Domain.UnitTests/Instructors/AuthenticationInstructorTests.cs, Submarine Domain/Domain/Instructors/Authentication/AuthenticationInstructor.cs, Submarine Domain/Domain/Instructors/Authentication/IAuthenticationInstructor.cs
=> SUBAPI-115: Restricted Duplicate User Registrations

Submarine API/Api.Abstractions.Interchange.UnitTests/Authentication/Register/RegisterRequestExtensionTests.cs, Submarine API/Api.Abstractions.Interchange/Authentication/Register/RegisterRequestExtensions.cs, Submarine API/Api.Abstractions.Swagger/Examples/GetUserRequestExamplesProvider.cs, Submarine API/Api.Abstractions.Swagger/Examples/RegisterRequestExamplesProvider.cs, Submarine API/Api.Abstractions/Middleware/ExceptionMiddleware.cs, Submarine API/Api.IntegrationTests/Controllers/AuthenticationControllerTests.cs, Submarine Abstractions/Abstractions.Interchange.TestPack/Builders/TestRegisterRequestBuilder.cs, Submarine Abstractions/Abstractions.Interchange/Requests/Authentication/RegisterRequest.cs, Submarine Domain Authentication/Domain.Authentication.UnitTests/Queries/GenerateBearerToken/GenerateBearerTokenQueryHandlerTests.cs, Submarine Domain Authentication/Domain.Authentication.UnitTests/Queries/HashText/HashTextQueryHandlerTests.cs, Submarine Domain Authentication/Domain.Authentication/Queries/GenerateBearerToken/GenerateBearerTokenQueryHandler.cs, Submarine Domain Authentication/Domain.Authentication/SubmarineRegisteredClaimNames.cs, Submarine Domain License/Domain.License.IntegrationTests/Queries/GetLicenseByProductKeyQueryHandlerTests.cs, Submarine Domain/Domain.UnitTests/Instructors/AuthenticationInstructorTests.cs, Submarine Domain/Domain.UnitTests/Instructors/UserInstructorTests.cs, Submarine Domain/Domain/Instructors/Authentication/AuthenticationInstructor.cs, Test Packs/IntegrationTestPack/Builders/TestBearerTokenBuilder.cs
=> SUBAPI-123: Removed User Name / Friendly Name from RegisterRequest

Submarine API/Api.Abstractions/Attributes/DiagnoseaRouteAttribute.cs, Submarine API/Api/Controllers/AuthenticationController.cs, Submarine API/Api/Controllers/LicenseController.cs, Submarine API/Api/Controllers/UserController.cs
=> SUBAPI-146: Added DiagnoseaRouteAttribute

Submarine Domain License/Domain.License.IntegrationTests/Queries/GetLicenseById/GetLicenseByIdQueryHandlerTests.cs, Submarine Domain License/Domain.License.UnitTests/Queries/GetLicenseById/GetLicenseByIdQueryBuilderTests.cs, Submarine Domain License/Domain.License/Queries/GetLicenseById/GetLicenseByIdQuery.cs, Submarine Domain License/Domain.License/Queries/GetLicenseById/GetLicenseByIdQueryBuilder.cs, Submarine Domain License/Domain.License/Queries/GetLicenseById/GetLicenseByIdQueryHandler.cs
=> SUBAPI-151: Get License By ID

Submarine Abstractions/Abstractions.Exceptions/LicenseExceptionMessages.cs, Submarine Domain License/Domain.License/Dtos/LicenseDto.cs, Submarine Domain License/Domain.License/Dtos/LicenseProductDto.cs, Submarine Domain License/Domain.License/Extensions/LicenseEntityExtensions.cs, Submarine Domain License/Domain.License/Extensions/LicenseProductEntityExtensions.cs, Submarine Domain/Domain.UnitTests/Instructors/LicenceInstructorTests.cs, Submarine Domain/Domain/Instructors/License/ILicenseInstructor.cs, Submarine Domain/Domain/Instructors/License/LicenseInstructor.cs
=> SUBAPI-125: Added License Instructor Method to Get License By ID

Submarine Abstractions/Abstractions.Exceptions/LicenseExceptionMessages.cs, Submarine Domain/Domain.UnitTests/Instructors/LicenceInstructorTests.cs, Submarine Domain/Domain/Instructors/License/ILicenseInstructor.cs, Submarine Domain/Domain/Instructors/License/LicenseInstructor.cs
=> SUBAPI-160: Added Method to Get License By User ID

Submarine Domain/Domain.UnitTests/Instructors/AuthenticationInstructorTests.cs, Submarine Domain/Domain/Instructors/Authentication/AuthenticationInstructor.cs
=> SUBAPI-163: Filtered Licensed Products Applied to JWT via Expiry

Domain.Supply/Entities/FiltrationSupply/FiltrationSupplyEntity.cs, Domain.Water/Domain.Water.csproj, Domain.Water/Entities/WaterCycleEntity.cs, Domain.Water/Entities/WaterEntity.cs, Domain.Water/Entities/WaterLevel/WaterBacterialLevelEntity.cs, Domain.Water/Entities/WaterLevel/WaterLevelEntity.cs, Domain.Water/Entities/WaterLevel/WaterMineralLevelEntity.cs, Submarine Abstractions/Abstractions/Enums/Supply/FiltrationSupplyType.cs, Submarine Abstractions/Abstractions/Enums/Water/WaterCycleStage.cs, Submarine.Api.sln
=> SUBAPI-172: Added Water Entity

Submarine Abstractions/Abstractions.Exceptions/TankExceptionMessages.cs, Submarine Domain Tank/Domain.Tank.UnitTests/Extensions/TankEntityExtensionTests.cs, Submarine Domain Tank/Domain.Tank.UnitTests/Extensions/TankLivestockStubExtensionTests.cs, Submarine Domain Tank/Domain.Tank.UnitTests/Extensions/TankSupplyStubExtensionTests.cs, Submarine Domain Tank/Domain.Tank.UnitTests/Extensions/TankWaterLevelStubExtensionTests.cs, Submarine Domain Tank/Domain.Tank.UnitTests/Extensions/TankWaterStubExtensionTests.cs, Submarine Domain Tank/Domain.Tank/Domain.Tank.csproj, Submarine Domain Tank/Domain.Tank/Dtos/TankDto.cs, Submarine Domain Tank/Domain.Tank/Dtos/TankLivestockDto.cs, Submarine Domain Tank/Domain.Tank/Dtos/TankSupplyDto.cs, Submarine Domain Tank/Domain.Tank/Dtos/TankWaterDto.cs, Submarine Domain Tank/Domain.Tank/Dtos/TankWaterLevelDto.cs, Submarine Domain Tank/Domain.Tank/Extensions/TankEntityExtensions.cs, Submarine Domain Tank/Domain.Tank/Extensions/TankLivestockStubExtensions.cs, Submarine Domain Tank/Domain.Tank/Extensions/TankSupplyStubExtensions.cs, Submarine Domain Tank/Domain.Tank/Extensions/TankWaterLevelStubExtensions.cs, Submarine Domain Tank/Domain.Tank/Extensions/TankWaterStubExtensions.cs, Submarine Domain/Domain.UnitTests/Instructors/LicenceInstructorTests.cs, Submarine Domain/Domain.UnitTests/Instructors/TankInstructorTests.cs, Submarine Domain/Domain/Domain.csproj, Submarine Domain/Domain/Instructors/Tank/ITankInstructor.cs, Submarine Domain/Domain/Instructors/Tank/TankInstructor.cs
=> SUBAPI-177: Added GetByUserId to Tank Instructor

Submarine API/Api.Abstractions.Authentication/Extensions/ClaimsPrincipalExtensions.cs, Submarine API/Api.Abstractions.Interchange.UnitTests/Tank/TankDtoExtensionTests.cs, Submarine API/Api.Abstractions.Interchange.UnitTests/Tank/TankLivestockDtoExtensionTests.cs, Submarine API/Api.Abstractions.Interchange.UnitTests/Tank/TankSupplyDtoExtensionTests.cs, Submarine API/Api.Abstractions.Interchange.UnitTests/Tank/TankWaterDtoExtensionTests.cs, Submarine API/Api.Abstractions.Interchange.UnitTests/Tank/TankWaterLevelDtoExtensionTests.cs, Submarine API/Api.Abstractions.Interchange/Api.Abstractions.Interchange.csproj, Submarine API/Api.Abstractions.Interchange/Tank/TankDtoExtensions.cs, Submarine API/Api.Abstractions.Interchange/Tank/TankLivestockDtoExtensions.cs, Submarine API/Api.Abstractions.Interchange/Tank/TankSupplyResponseExtension.cs, Submarine API/Api.Abstractions.Interchange/Tank/TankWaterDtoExtensions.cs, Submarine API/Api.Abstractions.Interchange/Tank/TankWaterLevelDtoExtensions.cs, Submarine API/Api.IntegrationTests/Controllers/TankControllerTests.cs, Submarine API/Api/Controllers/TankController.cs, Submarine Abstractions/Abstraction.Routes/RouteConstants.cs, Submarine Abstractions/Abstractions.Interchange/Responses/Tank/TankLivestockResponse.cs, Submarine Abstractions/Abstractions.Interchange/Responses/Tank/TankResponse.cs, Submarine Abstractions/Abstractions.Interchange/Responses/Tank/TankSupplyResponse.cs, Submarine Abstractions/Abstractions.Interchange/Responses/Tank/TankWaterLevelResponse.cs, Submarine Abstractions/Abstractions.Interchange/Responses/Tank/TankWaterResponse.cs, Submarine Domain Abstractions/Domain.Abstractions/CollectionConstants.cs, Submarine Domain Tank/Domain.Tank/Extensions/TankEntityExtensions.cs, Submarine Domain Tank/Domain.Tank/Extensions/TankWaterStubExtensions.cs, Submarine Domain/Domain/Extensions/ServiceCollectionExtensions.cs, Test Packs/IntegrationTestPack/Builders/TestBearerTokenBuilder.cs
=> SUBAPI-179: Added GetByUserId to TankController
